services:
  my_service:
    image: clockworklabs/spacetimedb:latest
    volumes:
      - ./data:/stdb
      - ./keys:/etc/spacetimedb
    ports:
      - "80:3000"
    command: ["start", "--data-dir=/stdb"]
